# Generated by Django 3.0.5 on 2024-10-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_auto_20240925_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='razer_order_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
